version: '3.8'

services:
  db:
    image: postgres
    container_name: marathon_pg
    environment:
      - POSTGRES_DB=marathon_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Oleg2005!
    volumes:
      - postgres_data:/var/lib/postgresql/data


  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  app:
    build: .
    container_name: marathon_api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/marathon_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Oleg2005!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/marathon_db?Timezone=UTC
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=Oleg2005!
      - SPRING_FLYWAY_SCHEMAS=public
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=false
      - SPRING_FLYWAY_VALIDATE_ON_MIGRATE=false
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

volumes:
  postgres_data: