spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marathon_db?Timezone=UTC
    username: postgres
    password: P@ssword12345
    driver-class-name: org.postgresql.Driver
  flyway:
    user: postgres
    password: P@ssword12345
    schemas: public
    baseline-on-migrate: false
    url: jdbc:postgresql://localhost:5432/marathon_db?Timezone=UTC
    driver-class-name: org.postgresql.Driver
    clean-disabled: false
    validate-on-migrate: false
  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates/
    check-template-location: true

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.highlight_sql: true

---
spring:
  config:
    activate:
      on-profile: docker

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: notificationRequest:ani.beautymarathon.entity.NotificationRequest
        spring.json.add.type.headers: true
      retries: 3
      acks: all

---
spring:
  config:
    activate:
      on-profile: no-docker
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration